# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/v1c77"

[social.params]
icon = "brand-github"

[[social]]
identifier = "stackoverflow"
name = "Stack Overflow"
url = "https://stackoverflow.com/users/6382035/vi-ci"


[social.params]
icon = "brand-stackoverflow"

[[social]]
identifier = "telegram"
name = "telegram"
url = "https://t.me/v1c77"


[social.params]
icon = "brand-telegram"
